package com.sequenceiq.it.cloudbreak.newway.testcase.mock;

import static com.sequenceiq.it.cloudbreak.newway.context.RunningParameter.key;

import javax.ws.rs.BadRequestException;
import javax.ws.rs.ForbiddenException;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.sequenceiq.it.cloudbreak.newway.client.CredentialTestClient;
import com.sequenceiq.it.cloudbreak.newway.action.gateway.PlatformGatewaysTestAction;
import com.sequenceiq.it.cloudbreak.newway.context.Description;
import com.sequenceiq.it.cloudbreak.newway.context.MockedTestContext;
import com.sequenceiq.it.cloudbreak.newway.context.TestCaseDescription;
import com.sequenceiq.it.cloudbreak.newway.context.TestContext;
import com.sequenceiq.it.cloudbreak.newway.entity.credential.CredentialTestDto;
import com.sequenceiq.it.cloudbreak.newway.entity.gateway.PlatformGatewaysTestDto;
import com.sequenceiq.it.cloudbreak.newway.testcase.AbstractIntegrationTest;

public class GatewaysTest extends AbstractIntegrationTest {

    @BeforeMethod
    public void beforeMethod(Object[] data) {
        createDefaultUser((TestContext) data[0]);
    }

    @Test(dataProvider = TEST_CONTEXT_WITH_MOCK)
    @Description(
            given = "created a MOCK credential",
            when = "calling gateways endpoint with that credential for getting cloud gateways",
            then = "getting a list with mock gateways")
    public void testGetPlatformGatewaysByCredentialName(MockedTestContext testContext) {
        String credentialName = getNameGenerator().getRandomNameForResource();
        testContext
                .given(CredentialTestDto.class)
                .withName(credentialName)
                .when(CredentialTestClient::create)
                .given(PlatformGatewaysTestDto.class)
                .withCredentialName(credentialName)
                .when(PlatformGatewaysTestAction::getGateways);
    }

    @Test(dataProvider = "contextWithCredentialNameAndException")
    public void testGetPlatformGatewaysByCredentialNameWhenCredentialIsInvalid(MockedTestContext testContext, String credentialName,
        Class<Exception> exception, @Description TestCaseDescription testCaseDescription) {
        String exceptionKey = getNameGenerator().getRandomNameForResource();
        testContext
                .given(PlatformGatewaysTestDto.class)
                .withCredentialName(credentialName)
                .when(PlatformGatewaysTestAction::getGateways, key(exceptionKey))
                .expect(exception, key(exceptionKey))
                .validate();
    }

    @DataProvider(name = "contextWithCredentialNameAndException")
    public Object[][] provideInvalidAttributes() {
        return new Object[][]{
                {
                    getBean(MockedTestContext.class),
                    "",
                    BadRequestException.class,
                    new TestCaseDescription.TestCaseDescriptionBuilder()
                        .given("created a MOCK credential")
                        .when("calling gateways endpoint with a non existing credential for getting cloud gateways")
                        .then("getting a BadRequestException")
                },
                {
                    getBean(MockedTestContext.class),
                    null,
                    BadRequestException.class,
                    new TestCaseDescription.TestCaseDescriptionBuilder()
                        .given("Testing database with unsupported database type")
                        .when("calling gateways endpoint with a 'null' credential for getting cloud gateways")
                        .then("getting a BadRequestException")
                },
                {
                    getBean(MockedTestContext.class),
                    "andNowForSomethingCompletelyDifferent",
                    ForbiddenException.class,
                    new TestCaseDescription.TestCaseDescriptionBuilder()
                        .given("Testing database with unsupported database type")
                        .when("calling gateways endpoint with a credential which not related to that account for getting cloud gateways")
                        .then("getting a  ForbiddenException")
                }
        };
    }

}
